### ISSUE TITLE
Trouble getting things to work in Angular 6.0.3

### ISSUE THREAD

**Issue by arimus** [mattlewis92/angularx-flatpickr#17]
I've changed things to import flatpickr and wire up everything else as stated in the docs, including the changes in [issue 12](https://github.com/mattlewis92/angularx-flatpickr/issues/12), but still getting the following error:

```
HeadlessChrome 0.0.0 (Mac OS X 10.12.6) AddEventSlideComponent should create FAILED
	TypeError: this.flatpickr is not a function
	    at FlatpickrDirective.push../node_modules/angularx-flatpickr/esm5/angularx-flatpickr.js.FlatpickrDirective.ngAfterViewInit node_modules/angularx-flatpickr/esm5/angularx-flatpickr.js:286:1)
	    at callProviderLifecycles node_modules/@angular/core/fesm5/core.js:10414:1)
	    at callElementProvidersLifecycles node_modules/@angular/core/fesm5/core.js:10388:1)
	    at callLifecycleHooksChildrenFirst node_modules/@angular/core/fesm5/core.js:10378:1)
	    at checkAndUpdateView node_modules/@angular/core/fesm5/core.js:11316:1)
	    at callViewAction node_modules/@angular/core/fesm5/core.js:11548:1)
	    at execComponentViewsAction node_modules/@angular/core/fesm5/core.js:11490:1)
	    at checkAndUpdateView node_modules/@angular/core/fesm5/core.js:11313:1)
	    at callWithDebugContext node_modules/@angular/core/fesm5/core.js:12204:1)
HeadlessChrome 0.0.0 (Mac OS X 10.12.6) AddEventSlideComponent should create FAILED
	TypeError: this.flatpickr is not a function
	    at FlatpickrDirective.push../node_modules/angularx-flatpickr/esm5/angularx-flatpickr.js.FlatpickrDirective.ngAfterViewInit node_modules/angularx-flatpickr/esm5/angularx-flatpickr.js:286:1)
	    at callProviderLifecycles node_modules/@angular/core/fesm5/core.js:10414:1)
	    at callElementProvidersLifecycles node_modules/@angular/core/fesm5/core.js:10388:1)
	    at callLifecycleHooksChildrenFirst node_modules/@angular/core/fesm5/core.js:10378:1)
	    at checkAndUpdateView node_modules/@angular/core/fesm5/core.js:11316:1)
	    at callViewAction node_modules/@angular/core/fesm5/core.js:11548:1)
	    at execComponentViewsAction node_modules/@angular/core/fesm5/core.js:11490:1)
	    at checkAndUpdateView node_modules/@angular/core/fesm5/core.js:11313:1)
	    at callWithDebugContext node_modules/@angular/core/fesm5/core.js:12204:1)
	    at Object.debugCheckAndUpdateView [as checkAndUpdateView] node_modules/@angular/core/fesm5/core.js:11882:1)
HeadlessChrome 0.0.0 (Mac OS X 10.12.6): Executed 2 of 53 (1 FAILED) (0 secs / 0.85 secs)
```

Any ideas?

**Comment by arimus** [comment]
Looks like I had one more import inside of one of my spec tests that was not fixed up properly. Closing :)
